### ISSUE TITLE
$self is not passed to ajax route handlers

### ISSUE THREAD

**Issue by simbabque** [PerlDancer/Dancer2-Plugin-Ajax#7]
It is not possible to get `$self` in `ajax` route handlers, because there are no arguments passed to the handler. The following code produces an empty array ref `[]` in the Dancer log.

```perl
use Dancer2;
use Dancer2::Plugin::Ajax;

ajax '/' => sub {
  use Data::Printer;
  p @_;
};

dance;

__END__
curl --header 'X-Requested-With: XMLHttpRequest' localhost:3000/
```
If the `ajax` is replaced with `get`, `@_` will contain `$self` and `@args`.

**This behaviour should be consistent**, and `ajax` route handlers should provide `$self` and `@args`. 

It needs to be added in https://github.com/PerlDancer/Dancer2-Plugin-Ajax/blob/master/lib/Dancer2/Plugin/Ajax.pm#L46.

This was discovered in https://stackoverflow.com/q/53006485/1331451.

**Comment by cromedome** [comment]
Merged and released. Thanks so much!
